import Head from "next/head";
import { useState } from "react";
import DatePicker from "react-datepicker";

export default function Home() {
  const today = new Date().toISOString().split("T")[0];
  const [date, setDate] = useState("");
  const [startDate, setStartDate] = useState(new Date());

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>hello world</h1>
        <DatePicker
          selected={startDate}
          onChange={(date) => setStartDate(date)}
        />
      </main>
    </div>
  );
}
